[package]
name = "FVNN-Mini-NN-Verifier"
version = "0.0.1"
edition = "2024"

[lib]
name = "mininn_verifier"
path = "src/lib.rs"

[[bin]]
name = "mininn"
path = "src/cli/mod.rs"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
libm = "0.2"
ndarray = "0.17.2"
rand = "0.10.2"
rand_distr = "0.6.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.18"
zip = "8.6.0"
